#!/bin/bash

# --- 1. Collect Phase ---
echo "Welcome to the gas-fakes project setup."
echo "This script will guide you through creating your .env file for testing."
echo "Please provide the following configuration values."
echo "Some values are required for the test suite to run correctly."
echo

# --- Required values ---
read -p "Enter your GCP Project ID: " gcp_project_id
if [ -z "$gcp_project_id" ]; then
    echo "Error: GCP Project ID is required." >&2
    exit 1
fi

read -p "Enter a Drive File ID you have read access to (for testing ADC): " drive_test_file_id
if [ -z "$drive_test_file_id" ]; then
    echo "Error: Drive File ID is required." >&2
    exit 1
fi

read -p "Enter a test Drive Folder Name you have write access to: " test_folder_name
if [ -z "$test_folder_name" ]; then
    echo "Error: Test Folder Name is required." >&2
    exit 1
fi

read -p "Enter the ID of that test Drive Folder: " test_folder_id
if [ -z "$test_folder_id" ]; then
    echo "Error: Test Folder ID is required." >&2
    exit 1
fi

# --- Optional values with defaults ---
read -p "Enter the number of files in that folder [0]: " test_folder_files
test_folder_files=${test_folder_files:-0}

read -p "Enter a viewer email for permission tests [viewer@mcpher.com]: " scratch_viewer
scratch_viewer=${scratch_viewer:-"viewer@mcpher.com"}

read -p "Enter an editor email for permission tests [editor@mcpher.com]: " scratch_editor
scratch_editor=${scratch_editor:-"editor@mcpher.com"}

read -p "Enter a second viewer email [viewer2@mcpher.com]: " scratch_b_viewer
scratch_b_viewer=${scratch_b_viewer:-"viewer2@mcpher.com"}

read -p "Enter a second editor email [editor2@mcpher.com]: " scratch_b_editor
scratch_b_editor=${scratch_b_editor:-"editor2@mcpher.com"}

read -p "Enter min PDFs in root for tests [20]: " min_root_pdfs
min_root_pdfs=${min_root_pdfs:-20}

read -p "Enter min PDFs total for tests [400]: " min_pdfs
min_pdfs=${min_pdfs:-400}

read -p "Enter min folders in root for tests [5]: " min_folders_root
min_folders_root=${min_folders_root:-5}


# --- 2. Confirm Phase ---
echo
echo "The following configuration will be written to .env:"
echo "================================================="
echo "# User-specific values"
echo "GCP_PROJECT_ID=${gcp_project_id}"
echo "DRIVE_TEST_FILE_ID=${drive_test_file_id}"
echo "TEST_FOLDER_NAME=\"${test_folder_name}\""
echo "TEST_FOLDER_ID=${test_folder_id}"
echo "TEST_FOLDER_FILES=${test_folder_files}"
echo "SCRATCH_VIEWER=${scratch_viewer}"
echo "SCRATCH_EDITOR=${scratch_editor}"
echo "SCRATCH_B_VIEWER=${scratch_b_viewer}"
echo "SCRATCH_B_EDITOR=${scratch_b_editor}"
echo "MIN_ROOT_PDFS=${min_root_pdfs}"
echo "MIN_PDFS=${min_pdfs}"
echo "MIN_FOLDERS_ROOT=${min_folders_root}"
echo
echo "# Shared and static values will also be included."
echo "================================================="
echo

read -p "Proceed with creating the .env file? (y/N) " confirm
if [[ ! "$confirm" =~ ^[yY](es)?$ ]]; then
    echo "Setup aborted. No file was written."
    exit 0
fi


# --- 3. Commit Phase ---
ENV_FILE=".env"
TEMP_ENV_FILE="${ENV_FILE}.tmp"

# Using a heredoc to write the complete file content.
cat > "$TEMP_ENV_FILE" << EOL
# Auto-generated by setup.sh on $(date)

# --- User-specific values ---
# Required for authentication and core tests
GCP_PROJECT_ID="${gcp_project_id}"
DRIVE_TEST_FILE_ID="${drive_test_file_id}"

# Required for file/folder manipulation tests
TEST_FOLDER_NAME="${test_folder_name}"
TEST_FOLDER_ID="${test_folder_id}"
TEST_FOLDER_FILES=${test_folder_files}

# For permission tests
SCRATCH_VIEWER="${scratch_viewer}"
SCRATCH_EDITOR="${scratch_editor}"
SCRATCH_B_VIEWER="${scratch_b_viewer}"
SCRATCH_B_EDITOR="${scratch_b_editor}"

# For iterator/search tests (adjust to your Drive content)
MIN_ROOT_PDFS=${min_root_pdfs}
MIN_PDFS=${min_pdfs}
MIN_FOLDERS_ROOT=${min_folders_root}

# --- Static auth config ---
# we'll use the default config for application default credentials
# probably dont need to change these
AC=default
DEFAULT_SCOPES="https://www.googleapis.com/auth/userinfo.email,openid,https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/sqlservice.login"
EXTRA_SCOPES=",https://www.googleapis.com/auth/drive,https://www.googleapis.com/auth/spreadsheets"

# --- Shared test file fixtures (read-only) ---
TEST_BORDERS_ID=1hRGdrYHEPixXTuQLeL3Z0qGRZVs_8ojMIm6D4KrCh1o
TEST_AIRPORTS_ID=1h9IGIShgVBVUrUjjawk5MaCEQte_7t32XeEP1Z5jXKQ
TEXT_FILE_NAME="fake.txt"
TEXT_FILE_ID=1142Vn7W-pGl5nWLpUSkpOB82JDiz9R6p
TEXT_FILE_TYPE="text/plain"
TEXT_FILE_CONTENT="foo is not bar"
TEST_SHEET_ID=1DlKpVVYCrCPNfRbGsz6N_K3oPTgdC9gQIKi0aNb42uI
TEST_SHEET_NAME="sharedlibraries"
PDF_ID=17t4ep9Jt6jRyDx0KlxMhHQNGZ3whg6GS

# --- Test behavior ---
# Set to 0 to preserve test files for debugging
CLEAN=1
EOL

# Atomically rename the temp file to the final .env file.
mv "$TEMP_ENV_FILE" "$ENV_FILE"

echo
echo "✅ The .env file has been created successfully."
echo "You can now run 'npm install && npm test' to run the test suite."