// Apps Script CriteriaType	to Sheets API Condition.type - this was mainly nonsense - it originally came from gemini but i've had t make lots of chenges so will probably abandon
const xx = { 
"BOOLEAN":"BOOLEAN",
"DATE_EQUAL_TO":"DATE_EQUAL",
"DATE_AFTER":"DATE_GREATER",
"DATE_AFTER_OR_EQUAL_TO":"DATE_GREATER_THAN_EQ",
"DATE_BEFORE":"DATE_LESS",
"DATE_BEFORE_OR_EQUAL_TO":"DATE_LESS_THAN_EQ",
"DATE_BETWEEN":"DATE_BETWEEN",
"DATE_NOT_BETWEEN":"DATE_NOT_BETWEEN",
"TEXT_CONTAINS":"TEXT_CONTAINS",
"TEXT_DOES_NOT_CONTAIN":"TEXT_NOT_CONTAINS",
"TEXT_EQUAL_TO":"TEXT_EQUAL",
"NUMBER_EQUAL_TO":"NUMBER_EQUAL",
"NUMBER_GREATER_THAN":"NUMBER_GREATER",
"NUMBER_GREATER_THAN_OR_EQUAL_TO":"NUMBER_GREATER_THAN_EQ",
"NUMBER_LESS_THAN":"NUMBER_LESS",
"NUMBER_LESS_THAN_OR_EQUAL_TO":"NUMBER_LESS_THAN_EQ",
"NUMBER_BETWEEN":"NUMBER_BETWEEN",
"NUMBER_NOT_BETWEEN":"NUMBER_NOT_BETWEEN",
"VALUE_IN_LIST":"ONE_OF_LIST",
"VALUE_IN_RANGE":"ONE_OF_RANGE",
"CUSTOM_FORMULA":"CUSTOM_FORMULA",
"TEXT_LENGTH_GREATER_THAN":"TEXT_LENGTH_GREATER_THAN",
"TEXT_LENGTH_GREATER_THAN_OR_EQUAL_TO":"TEXT_LENGTH_GREATER_THAN_EQ",
"TEXT_LENGTH_LESS_THAN":"TEXT_LENGTH_LESS_THAN",
"TEXT_LENGTH_LESS_THAN_OR_EQUAL_TO":"TEXT_LENGTH_LESS_THAN_EQ",
"TEXT_LENGTH_EQUAL_TO":"TEXT_LENGTH_EQUAL",
"git":"TEXT_IS_VALID_EMAIL",
"TEXT_IS_VALID_URL":"TEXT_IS_VALID_URL",
"TIME_EQUAL_TO":"TIME_EQUAL",
"TIME_AFTER":"TIME_GREATER",
"TIME_AFTER_OR_EQUAL_TO":"TIME_GREATER_THAN_EQ",
"TIME_BEFORE":"TIME_LESS",
"TIME_BEFORE_OR_EQUAL_TO":"TIME_LESS_THAN_EQ",
"TIME_BETWEEN":"TIME_BETWEEN",
"TIME_NOT_BETWEEN":"TIME_NOT_BETWEEN",
"DATE_IS_VALID_DATE":"DATE_IS_VALID_DATE",
}

/*
these dont have direct equivalents in Sheets API
(Note: Sheets API doesn't have a strict "IS_NUMBER", DECIMAL is the closest for allowing any valid number)
IS_TEXT	(No direct equivalent, validation would likely be absent or use a custom formula)
IS_BLANK	(No direct equivalent, often handled with conditional formatting or custom formulas)
IS_NOT_BLANK	(No direct equivalent, often handled with conditional formatting or custom formulas)
NUMBER_IS_EVEN	(No direct equivalent, use CUSTOM_FORMULA with =ISEVEN(...))
NUMBER_IS_ODD	(No direct equivalent, use CUSTOM_FORMULA with =ISODD(...))
NUMBER_IS_PRIME	(No direct equivalent, use CUSTOM_FORMULA with a prime checking formula)
*/
