/**
 * Advanced sheets service
 */
import { Proxies } from '../../support/proxies.js'
import { notYetImplemented } from '../../support/helpers.js'
import { getAuthedClient } from '../spreadsheetapp/shapis.js'
import {newFakeAdvSheetsSpreadsheets} from './fakeadvsheetsspreadsheets.js'
/// <reference path="../typedefs.js"
/**
 * the advanced Sheets Apps Script service faked
 * @class FakeAdvSheets
 */


  
class FakeAdvSheets {
  constructor() {
    this.client = Proxies.guard(getAuthedClient())
    const props = [ 
      'newGridData',
      'newConditionalFormatRule',
      'newAddBandingRequest',
      'newEditors',
      'newDataSourceChartProperties',
      'newUnmergeCellsRequest',
      'newRequest',
      'newFilterView',
      'newRepeatCellRequest',
      'newBatchClearValuesByDataFilterRequest',
      'newAddChartRequest',
      'newPivotFilterSpec',
      'newDeleteNamedRangeRequest',
      'newConditionValue',
      'newLineStyle',
      'newDataSourceRefreshSchedule',
      'newUpdateEmbeddedObjectBorderRequest',
      'newUpdateCellsRequest',
      'newNamedRange',
      'newHistogramRule',
      'newPasteDataRequest',
      'newUpdateFilterViewRequest',
      'newDeleteBandingRequest',
      'newLink',
      'newAddDimensionGroupRequest',
      'newDataFilter',
      'newGridCoordinate',
      'newBatchUpdateValuesRequest',
      'newDataSourceObjectReferences',
      'newWaterfallChartSeries',
      'newSortRangeRequest',
      'newUpdateDimensionGroupRequest',
      'newAddSlicerRequest',
      'newBasicFilter',
      'newInterval',
      'newGridRange',
      'newDataSourceParameter',
      'newSourceAndDestination',
      'newCellFormat',
      'newDeveloperMetadataLocation',
      'newDataSource',
      'newAddNamedRangeRequest',
      'newBasicSeriesDataPointStyleOverride',
      'newOverlayPosition',
      'newDataExecutionStatus',
      'newProtectedRange',
      'newDuplicateSheetRequest',
      'newPointStyle',
      'newAutoFillRequest',
      'newChartAxisViewWindowOptions',
      'newScorecardChartSpec',
      'newUpdateSheetPropertiesRequest',
      'newTextRotation',
      'newChartSpec',
      'newUpdateProtectedRangeRequest',
      'newAddSheetRequest',
      'newBandingProperties',
      'newDataValidationRule',
      'newAddFilterViewRequest',
      'newDeveloperMetadataLookup',
      'newBandedRange',
      'newExtendedValue',
      'newAddDataSourceRequest',
      'newAutoResizeDimensionsRequest',
      'newChartData',
      'newTreemapChartColorScale',
      'newUpdateBandingRequest',
      'newChartCustomNumberFormatOptions',
      'newBooleanCondition',
      'newDataLabel',
      'newDuplicateFilterViewRequest',
      'newGradientRule',
      'newTrimWhitespaceRequest',
      'newBatchClearValuesRequest',
      'newLookerDataSourceSpec',
      'newTextToColumnsRequest',
      'newTimeOfDay',
      'newDataSourceObjectReference',
      'newPivotGroupValueMetadata',
      'newCandlestickDomain',
      'newChartGroupRule',
      'newDimensionRange',
      'newBorder',
      'newDeleteSheetRequest',
      'newCopyPasteRequest',
      'newDeleteDuplicatesRequest',
      'newUpdateDeveloperMetadataRequest',
      'newFilterSpec',
      'newEmbeddedObjectPosition',
      'newGetSpreadsheetByDataFilterRequest',
      'newSlicer',
      'newGridProperties',
      'newBasicChartDomain',
      'newUpdateDimensionPropertiesRequest',
      'newManualRule',
      'newRowData',
      'newSheetProperties',
      'newTextFormatRun',
      'newSheet',
      'newCandlestickChartSpec',
      'newMoveDimensionRequest',
      'newUpdateNamedRangeRequest',
      'newRefreshDataSourceRequest',
      'newBigQueryDataSourceSpec',
      'newEmbeddedObjectBorder',
      'newDataSourceRefreshWeeklySchedule',
      'newBubbleChartSpec',
      'newAddConditionalFormatRuleRequest',
      'newSpreadsheetProperties',
      'newWaterfallChartCustomSubtotal',
      'newBooleanRule',
      'newUpdateConditionalFormatRuleRequest',
      'newDateTimeRule',
      'newAppendDimensionRequest',
      'newDimensionGroup',
      'newTextPosition',
      'newColor',
      'newDataSourceRefreshDailySchedule',
      'newCutPasteRequest',
      'newTextFormat',
      'newInsertRangeRequest',
      'newRandomizeRangeRequest',
      'newPadding',
      'newWaterfallChartColumnStyle',
      'newDataSourceColumnReference',
      'newSearchDeveloperMetadataRequest',
      'newSlicerSpec',
      'newDeleteDimensionRequest',
      'newBigQueryTableSpec',
      'newSetBasicFilterRequest',
      'newPivotValue',
      'newHistogramSeries',
      'newSpreadsheetTheme',
      'newFindReplaceRequest',
      'newDeleteRangeRequest',
      'newClearBasicFilterRequest',
      'newPivotGroupRule',
      'newDataSourceSpec',
      'newWaterfallChartSpec',
      'newDeleteDimensionGroupRequest',
      'newBatchGetValuesByDataFilterRequest',
      'newCandlestickSeries',
      'newEmbeddedChart',
      'newCandlestickData',
      'newOrgChartSpec',
      'newDataSourceRefreshMonthlySchedule',
      'newChartSourceRange',
      'newDataSourceSheetProperties',
      'newDeleteProtectedRangeRequest',
      'newBorders',
      'newColorStyle',
      'newPivotTable',
      'newPivotGroup',
      'newCancelDataSourceRefreshRequest',
      'newHistogramChartSpec',
      'newValueRange',
      'newUpdateSlicerSpecRequest',
      'newUpdateDataSourceRequest',
      'newTreemapChartSpec',
      'newUpdateChartSpecRequest',
      'newMergeCellsRequest',
      'newErrorValue',
      'newBaselineValueFormat',
      'newBasicChartSeries',
      'newNumberFormat',
      'newAddProtectedRangeRequest',
      'newCopySheetToAnotherSpreadsheetRequest',
      'newFilterCriteria',
      'newDataSourceTable',
      'newDeleteDataSourceRequest',
      'newDataSourceSheetDimensionRange',
      'newSpreadsheet',
      'newKeyValueFormat',
      'newWaterfallChartDomain',
      'newCreateDeveloperMetadataRequest',
      'newUpdateEmbeddedObjectPositionRequest',
      'newClearValuesRequest',
      'newChartHistogramRule',
      'newDataFilterValueRange',
      'newIterativeCalculationSettings',
      'newPivotFilterCriteria',
      'newThemeColorPair',
      'newPivotGroupSortValueBucket',
      'newUpdateBordersRequest',
      'newAppendCellsRequest',
      'newDataSourceColumn',
      'newDeleteConditionalFormatRuleRequest',
      'newCellData',
      'newChartDateTimeRule',
      'newInsertDimensionRequest',
      'newBatchUpdateValuesByDataFilterRequest',
      'newSortSpec',
      'newDataSourceFormula',
      'newDeleteEmbeddedObjectRequest',
      'newBasicChartAxis',
      'newPivotGroupLimit',
      'newPieChartSpec',
      'newDeleteFilterViewRequest',
      'newDeveloperMetadata',
      'newBasicChartSpec',
      'newDeleteDeveloperMetadataRequest',
      'newManualRuleGroup',
      'newDimensionProperties',
      'newBigQueryQuerySpec',
      'newUpdateSpreadsheetPropertiesRequest',
      'newSetDataValidationRequest',
      'newInterpolationPoint',
      'newBatchUpdateSpreadsheetRequest' ]
      
      props.forEach(f => {
        this[f] = ()=> {
          return notYetImplemented()
        }
      })
    
  }
  toString() {
    return 'AdvancedServiceIdentifier{name=sheets, version=v4}'
  }
  getVersion() {
    return 'v4'
  }  
  get Spreadsheets () {
    return newFakeAdvSheetsSpreadsheets(this)
  }
}

export const newFakeAdvSheets = (...args) => Proxies.guard(new FakeAdvSheets(...args))

