import { Proxies } from '../../support/proxies.js';
import { Syncit } from '../../support/syncit.js';
import { newFakeJdbcResultSet } from './fakejdbcresultset.js';

class FakeJdbcStatement {
  constructor(connection, connectionId) {
    this.__fakeObjectType = 'JdbcStatement';
    this._connection = connection;
    this._connectionId = connectionId;
    this._isClosed = false;
    this._batch = [];
    this._fetchSize = 0;
    this._maxRows = 0;
    this._queryTimeout = 0;
    this._maxFieldSize = 0;
    this._fetchDirection = 1000; // FETCH_FORWARD
    this._isPoolable = false;
    this._lastUpdateCount = -1;
  }

  addBatch(sql) {
    if (this._isClosed) throw new Error('Statement is closed.');
    this._batch.push(sql);
  }

  executeBatch() {
    if (this._isClosed) throw new Error('Statement is closed.');
    const results = [];
    for (const sql of this._batch) {
      const result = Syncit.fxJdbcQuery(this._connectionId, sql);
      results.push(result.rowCount || 0);
    }
    this.clearBatch();
    return results;
  }

  clearBatch() {
    this._batch = [];
  }

  executeQuery(sql) {
    if (this._isClosed) throw new Error('Statement is closed.');
    
    // Fetch result synchronously from worker
    const result = Syncit.fxJdbcQuery(this._connectionId, sql);
    this._lastUpdateCount = -1;
    this._lastResultSet = newFakeJdbcResultSet(result);
    return this._lastResultSet;
  }

  execute(sql, autoGeneratedKeysOrIndexesOrNames) {
    if (this._isClosed) throw new Error('Statement is closed.');
    
    const result = Syncit.fxJdbcQuery(this._connectionId, sql);
    this._lastUpdateCount = result.rowCount || 0;
    if (result.fields && result.fields.length > 0) {
      this._lastResultSet = newFakeJdbcResultSet(result);
      return true;
    } else {
      this._lastResultSet = null;
      return false;
    }
  }

  executeUpdate(sql, autoGeneratedKeysOrIndexesOrNames) {
    if (this._isClosed) throw new Error('Statement is closed.');
    const result = Syncit.fxJdbcQuery(this._connectionId, sql);
    this._lastUpdateCount = result.rowCount;
    this._lastResultSet = null;
    return result.rowCount;
  }

  cancel() {
    // Stub: No-op for fake
  }

  clearWarnings() {
    // Stub: No-op for fake
  }

  getConnection() {
    return this._connection;
  }

  getFetchDirection() {
    return this._fetchDirection;
  }

  getFetchSize() {
    return this._fetchSize;
  }

  getGeneratedKeys() {
    // Return empty results as we don't currently track generated auto-increment IDs
    return newFakeJdbcResultSet({ fields: [], rows: [] });
  }

  getMaxFieldSize() {
    return this._maxFieldSize;
  }

  getMaxRows() {
    return this._maxRows;
  }

  getMoreResults(current) {
    // We only support one result set at a time per statement in this fake
    return false;
  }

  getQueryTimeout() {
    return this._queryTimeout;
  }

  getResultSetConcurrency() {
    return 1007; // CONCUR_READ_ONLY
  }

  getResultSetHoldability() {
    return 1; // HOLD_CURSORS_OVER_COMMIT
  }

  getResultSetType() {
    return 1003; // TYPE_FORWARD_ONLY
  }

  getWarnings() {
    return null;
  }

  isPoolable() {
    return this._isPoolable;
  }

  setCursorName(name) {
    // Stub: No-op for fake
  }

  setEscapeProcessing(enable) {
    // Stub: No-op for fake
  }

  setFetchDirection(direction) {
    this._fetchDirection = direction;
  }

  setFetchSize(rows) {
    this._fetchSize = rows;
  }

  setMaxFieldSize(max) {
    this._maxFieldSize = max;
  }

  setMaxRows(max) {
    this._maxRows = max;
  }

  setPoolable(poolable) {
    this._isPoolable = poolable;
  }

  setQueryTimeout(seconds) {
    this._queryTimeout = seconds;
  }

  getUpdateCount() {
    return this._lastUpdateCount || 0;
  }

  getResultSet() {
    return this._lastResultSet;
  }

  close() {
    this._isClosed = true;
    this._lastResultSet = null;
  }

  isClosed() {
    return this._isClosed;
  }
}

export const newFakeJdbcStatement = (...args) => Proxies.guard(new FakeJdbcStatement(...args));
